# Generated by Django 2.2.10 on 2022-05-31 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll_service_api', '0002_auto_20220531_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='poll_service_api.Question', verbose_name='Вопрос'),
        ),
    ]
