# Generated by Django 2.2.10 on 2022-06-01 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll_service_api', '0003_auto_20220531_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='date_of_answer',
        ),
    ]
